# cloud-nuke tests failing to clean up S3 buckets

**brikis98** commented *Oct 9, 2020*

Our Phx DevOps account is accumulating a bunch of `cloud-nuke-test-xxx` buckets... Something in the tests must be failing to do clean up. Note that #135 made a change to the S3 code recently, so perhaps it's related to that?
<br />
***


**yorinasub17** commented *Oct 14, 2020*

Ah I think I see the error. After investigating one of the build logs (https://app.circleci.com/pipelines/github/gruntwork-io/cloud-nuke/1676/workflows/95927868-7839-4188-a36b-ff64d490c88f/jobs/21370/steps) for one of the buckets that are left over (`cloud-nuke-test-zybci5euyoor`), it looks like the issue is in https://github.com/gruntwork-io/cloud-nuke/blob/b3be88760d6ce072d7dfb779bef9b286bf466767/aws/s3_test.go#L321

Specifically, for the failure tests, https://github.com/gruntwork-io/cloud-nuke/blob/b3be88760d6ce072d7dfb779bef9b286bf466767/aws/s3_test.go#L365 expectedly fails to nuke the bucket, but then we don't call that function again in the test with a valid input, which is why those buckets remain ü§¶ . And it is my fault, because I removed the clean up nuking call: https://github.com/gruntwork-io/cloud-nuke/pull/135/files#diff-952bc67643ea23fbc7dc172cc633a1b6d269674fd9d391ae5d78066aa3104a1cL355 ü§¶ ü§¶ ü§¶ 
***

**ina-stoyanova** commented *Oct 14, 2020*

After syncing up with @yorinasub17 & @infraredgirl, we've agreed that the cause (as pointed by @yorinasub17 above, and after some investigation this afternoon) is the lack of cleanup of S3 buckets after testing S3 buckets creation with invalid bucket args. 

We agreed to revert the change. 
***

**ina-stoyanova** commented *Oct 16, 2020*

^ PR above fixes this üëç 
***

